### ISSUE TITLE
Open source the server part

### ISSUE THREAD

**Issue by leonklingele** [lukin0110/push#13]
Is the server open source as well? :)

**Comment by lukin0110** [comment]
Not yet. The plan is to open source the server part as well, but the code needs some cleanup first. But its written in Go as well.

**Comment by lukin0110** [comment]
@leonklingele it's open sourced on https://github.com/TheWebMonks/push.kiwi. Keep in mind that it's my first project in Go. It's a very simple file upload server. All comments are welcome!
